security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Custom\CMSBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: ROLE_ADMIN }
        user_db:
            entity: { class: CustomCMSBundle:User, property: username }
    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /cms/page
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /cms/user, roles: ROLE_ADMIN }
        - { path: /cms/category, roles: ROLE_ADMIN }
        - { path: /cms/page, roles: ROLE_USER }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
## To get started with security, check out the documentation:
## http://symfony.com/doc/current/security.html
#security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#        Custom\CMSBundle\Entity\User: bcrypt
#    role_hierarchy:
#        ROLE_ADMIN: [ROLE_USER]
#    providers:
#        chain_providers:
#            chain:
#                providers: [in memory,user_db]
#        in_memory:
#            memory:
#                users:
#                    admin: {password: adminpass, roles: ROLE_ADMIN }
#        user_db:
#            entity: { class: CustomCMSBundle:User, property: username }
#    firewalls:
#        main:
#            pattern: /.*
#            form_login:
#                login_path: /login
#                check_path: /login_check
#                default_target_path: /
#            logout:
#                path: /logout
#                target: /
#            security: true
#            anonymous: true
#    access_control:
#        - {path: /login,roles: IS_AUTHETICATED_ANONYMOUSLY }
#        - {path: /cms/user,roles: ROLE_ADMIN }
#        - {path: /.*,roles: IS_AUTHETICATED_ANONYMOUSLY }
#
#
#
##    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
##    providers:
##        in_memory:
##            memory: ~
##
##    firewalls:
##        # disables authentication for assets and the profiler, adapt it according to your needs
##        dev:
##            pattern: ^/(_(profiler|wdt)|css|images|js)/
##            security: false
##
##        main:
##            anonymous: ~
##            # activate different ways to authenticate
##
##            # http_basic: ~
##            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
##
##            # form_login: ~
##            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
